import type { ScanResult, Finding } from '@sentinel/core';
import pico from 'picocolors';

function colorizeScore(score: number, text: string | number): string {
  if (score >= 80) return pico.green(text);
  if (score >= 60) return pico.yellow(text);
  if (score >= 40) return pico.red(text);
  return pico.bold(pico.red(text));
}

function severityTag(finding: Finding): string {
  const tag = `[${finding.severity.toUpperCase()}]`;
  switch (finding.severity) {
    case 'critical': return pico.bold(pico.red(tag));
    case 'high': return pico.red(tag);
    case 'medium': return pico.yellow(tag);
    case 'low': return pico.green(tag);
    case 'info': return pico.cyan(tag);
    default: return tag;
  }
}

export function renderTerminalReport(result: ScanResult): string {
  const { summary } = result;
  const lines: string[] = [];

  // Header
  lines.push('');
  lines.push(pico.bold(pico.cyan('🔍 Sentinel Security Report')));
  lines.push(pico.dim('═'.repeat(60)));
  lines.push(`${pico.bold('Target:')} ${result.target}`);
  lines.push(`${pico.bold('Scan ID:')} ${result.id}`);
  lines.push(`${pico.bold('Time:')} ${result.timestamp}`);
  lines.push(`${pico.bold('Files:')} ${result.filesScanned} scanned, ${result.filesSkipped} skipped`);
  lines.push('');

  // Scores
  lines.push(pico.bold('Scores:'));
  lines.push(`  ${pico.bold('Repository Health:')} ${colorizeScore(summary.scores.repositoryHealth, `${summary.scores.repositoryHealth}%`)}`);
  lines.push(`  ${pico.bold('AI Confidence:')}    ${colorizeScore(summary.scores.aiConfidence, `${summary.scores.aiConfidence}%`)}`);
  lines.push(`  ${pico.bold('Risk Score:')}        ${colorizeScore(100 - summary.scores.risk, `${summary.scores.risk}%`)}`);
  lines.push('');

  // Summary counts
  lines.push(pico.bold('Findings Summary:'));
  if (summary.total === 0) {
    lines.push(`  ${pico.green('✓ No findings detected')}`);
  } else {
    lines.push(`  ${pico.bold('Total:')} ${summary.total}`);
    if (summary.critical > 0) lines.push(`  ${pico.bold(pico.red(`Critical: ${summary.critical}`))}`);
    if (summary.high > 0) lines.push(`  ${pico.red(`High: ${summary.high}`)}`);
    if (summary.medium > 0) lines.push(`  ${pico.yellow(`Medium: ${summary.medium}`)}`);
    if (summary.low > 0) lines.push(`  ${pico.green(`Low: ${summary.low}`)}`);
    if (summary.info > 0) lines.push(`  ${pico.cyan(`Info: ${summary.info}`)}`);
  }
  lines.push('');

  // Findings list
  if (result.findings.length > 0) {
    lines.push(pico.bold('Findings:'));
    lines.push('');

    for (const finding of result.findings) {
      lines.push(`  ${severityTag(finding)} ${finding.message}`);
      lines.push(`        ${pico.dim(`${finding.file}:${finding.line}:${finding.column}`)}`);
      lines.push(`        ${pico.dim(`Rule: ${finding.rule} | ${finding.category}`)}`);
      if (finding.snippet) {
        lines.push(`        ${pico.dim('Snippet:')} ${finding.snippet.slice(0, 120)}`);
      }
      if (finding.suggestedFix) {
        lines.push(`        ${pico.cyan(`💡 ${finding.suggestedFix}`)}`);
      }
      lines.push('');
    }
  }

  lines.push(pico.dim('═'.repeat(60)));
  lines.push(pico.dim('Generated by Sentinel — AI Software Engineering Safety Platform'));
  lines.push('');

  return lines.join('\n');
}
